import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import './globals.css'

//components
import Navbar from './components/Navbar/Navbar'
import Footer from './components/Footer/Footer'


const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Designo multi page website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
